from environs import Env

env = Env()
env.read_env()

DEBUG = env.bool('DEBUG', default=False)

# === REDIS ===

PRICE_CHANNEL = 15
SYSTEM_CHANNEL = 14
ORDER_CHANNEL = 12

REDIS_HOST = env('REDIS_HOST')
REDIS_PORT = env('REDIS_PORT')
REDIS_DB_NUMBER = env.int('REDIS_DB_NUMBER', default=3)

# === TELSTRA SMS ===

TELSTRA_CLIENT_KEY = env.str('TELSTRA_CLIENT_KEY')
TELSTRA_CLIENT_SECRET = env.str('TELSTRA_CLIENT_SECRET')

# === TELEGRAM BOT ===

TELEGRAM_TOKEN = env.str('TELEGRAM_TOKEN')
MY_CHAT_ID = env.str('MY_CHAT_ID')


# === Aliyun ===

ALIYUN_ACCESS_KEY_ID=env.str('ALIYUN_ACCESS_KEY_ID')
ALIYUN_ACCESS_KEY_SECRET=env.str('ALIYUN_ACCESS_KEY_SECRET')

ALIYUN_EMAIL_HOST=env.str('TELEGRAM_TOKEN')
ALIYUN_SINGLE_EMAIL_USERNAME=env.str('ALIYUN_SINGLE_EMAIL_USERNAME')
ALIYUN_SINGLE_EMAIL_PASSWORD=env.str('ALIYUN_SINGLE_EMAIL_PASSWORD')
ALIYUN_BATCH_EMAIL_USERNAME=env.str('ALIYUN_BATCH_EMAIL_USERNAME')
ALIYUN_BATCH_EMAIL_PASSWORD=env.str('ALIYUN_BATCH_EMAIL_PASSWORD')

# === ADMIN ===

ADMIN_EMAIL = env('ADMIN_EMAIL')
ADMIN_MOBILE_NUMBER = env.str('ADMIN_MOBILE_NUMBER')
