# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sms.proto',
  package='jarvis.sms',
  syntax='proto3',
  serialized_options=_b('\n\njarvis.smsB\016JarvisSMSProto\242\002\tJARVISSMS'),
  serialized_pb=_b('\n\tsms.proto\x12\njarvis.sms\"C\n\x0c\x41uSMSRequest\x12\x15\n\rmobile_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03\x61pp\x18\x03 \x01(\t\"1\n\x11\x41uAdminSMSRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03\x61pp\x18\x02 \x01(\t\"0\n\rAuSMSResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"\x89\x01\n\x0c\x43nSMSRequest\x12<\n\x0emobile_numbers\x18\x01 \x03(\x0b\x32$.jarvis.sms.CnSMSRequest.PhoneNumber\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03\x61pp\x18\x03 \x01(\t\x1a\x1d\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\"0\n\rCnSMSResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xc7\x01\n\x03SMS\x12\x44\n\x08SMSAdmin\x12\x1d.jarvis.sms.AuAdminSMSRequest\x1a\x19.jarvis.sms.AuSMSResponse\x12<\n\x05SMSAu\x12\x18.jarvis.sms.AuSMSRequest\x1a\x19.jarvis.sms.AuSMSResponse\x12<\n\x05SMSCn\x12\x18.jarvis.sms.CnSMSRequest\x1a\x19.jarvis.sms.CnSMSResponseB(\n\njarvis.smsB\x0eJarvisSMSProto\xa2\x02\tJARVISSMSb\x06proto3')
)




_AUSMSREQUEST = _descriptor.Descriptor(
  name='AuSMSRequest',
  full_name='jarvis.sms.AuSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_number', full_name='jarvis.sms.AuSMSRequest.mobile_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='jarvis.sms.AuSMSRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.AuSMSRequest.app', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=92,
)


_AUADMINSMSREQUEST = _descriptor.Descriptor(
  name='AuAdminSMSRequest',
  full_name='jarvis.sms.AuAdminSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='jarvis.sms.AuAdminSMSRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.AuAdminSMSRequest.app', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=143,
)


_AUSMSRESPONSE = _descriptor.Descriptor(
  name='AuSMSResponse',
  full_name='jarvis.sms.AuSMSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='jarvis.sms.AuSMSResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='jarvis.sms.AuSMSResponse.detail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=193,
)


_CNSMSREQUEST_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='jarvis.sms.CnSMSRequest.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='jarvis.sms.CnSMSRequest.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=333,
)

_CNSMSREQUEST = _descriptor.Descriptor(
  name='CnSMSRequest',
  full_name='jarvis.sms.CnSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_numbers', full_name='jarvis.sms.CnSMSRequest.mobile_numbers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='jarvis.sms.CnSMSRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.CnSMSRequest.app', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CNSMSREQUEST_PHONENUMBER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=333,
)


_CNSMSRESPONSE = _descriptor.Descriptor(
  name='CnSMSResponse',
  full_name='jarvis.sms.CnSMSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='jarvis.sms.CnSMSResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='jarvis.sms.CnSMSResponse.detail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=383,
)

_CNSMSREQUEST_PHONENUMBER.containing_type = _CNSMSREQUEST
_CNSMSREQUEST.fields_by_name['mobile_numbers'].message_type = _CNSMSREQUEST_PHONENUMBER
DESCRIPTOR.message_types_by_name['AuSMSRequest'] = _AUSMSREQUEST
DESCRIPTOR.message_types_by_name['AuAdminSMSRequest'] = _AUADMINSMSREQUEST
DESCRIPTOR.message_types_by_name['AuSMSResponse'] = _AUSMSRESPONSE
DESCRIPTOR.message_types_by_name['CnSMSRequest'] = _CNSMSREQUEST
DESCRIPTOR.message_types_by_name['CnSMSResponse'] = _CNSMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuSMSRequest = _reflection.GeneratedProtocolMessageType('AuSMSRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuSMSRequest)
  })
_sym_db.RegisterMessage(AuSMSRequest)

AuAdminSMSRequest = _reflection.GeneratedProtocolMessageType('AuAdminSMSRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUADMINSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuAdminSMSRequest)
  })
_sym_db.RegisterMessage(AuAdminSMSRequest)

AuSMSResponse = _reflection.GeneratedProtocolMessageType('AuSMSResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUSMSRESPONSE,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuSMSResponse)
  })
_sym_db.RegisterMessage(AuSMSResponse)

CnSMSRequest = _reflection.GeneratedProtocolMessageType('CnSMSRequest', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _CNSMSREQUEST_PHONENUMBER,
    '__module__' : 'sms_pb2'
    # @@protoc_insertion_point(class_scope:jarvis.sms.CnSMSRequest.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _CNSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.CnSMSRequest)
  })
_sym_db.RegisterMessage(CnSMSRequest)
_sym_db.RegisterMessage(CnSMSRequest.PhoneNumber)

CnSMSResponse = _reflection.GeneratedProtocolMessageType('CnSMSResponse', (_message.Message,), {
  'DESCRIPTOR' : _CNSMSRESPONSE,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.CnSMSResponse)
  })
_sym_db.RegisterMessage(CnSMSResponse)


DESCRIPTOR._options = None

_SMS = _descriptor.ServiceDescriptor(
  name='SMS',
  full_name='jarvis.sms.SMS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=386,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='SMSAdmin',
    full_name='jarvis.sms.SMS.SMSAdmin',
    index=0,
    containing_service=None,
    input_type=_AUADMINSMSREQUEST,
    output_type=_AUSMSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SMSAu',
    full_name='jarvis.sms.SMS.SMSAu',
    index=1,
    containing_service=None,
    input_type=_AUSMSREQUEST,
    output_type=_AUSMSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SMSCn',
    full_name='jarvis.sms.SMS.SMSCn',
    index=2,
    containing_service=None,
    input_type=_CNSMSREQUEST,
    output_type=_CNSMSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMS)

DESCRIPTOR.services_by_name['SMS'] = _SMS

# @@protoc_insertion_point(module_scope)
