# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sms.proto',
  package='jarvis.sms',
  syntax='proto3',
  serialized_options=_b('\n\njarvis.smsB\016JarvisSMSProto\242\002\tJARVISSMS'),
  serialized_pb=_b('\n\tsms.proto\x12\njarvis.sms\"C\n\x0c\x41uSMSRequest\x12\x15\n\rmobile_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03\x61pp\x18\x03 \x01(\t\"1\n\x11\x41uAdminSMSRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03\x61pp\x18\x02 \x01(\t\"0\n\rAuSMSResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"\xc4\x01\n\x10\x41liyunSMSRequest\x12@\n\x0emobile_numbers\x18\x01 \x03(\x0b\x32(.jarvis.sms.AliyunSMSRequest.PhoneNumber\x12\x15\n\rtemplate_code\x18\x02 \x01(\t\x12\x16\n\x0etemplate_param\x18\x03 \x01(\t\x12\x13\n\x0b\x62usiness_id\x18\x04 \x01(\t\x12\x0b\n\x03\x61pp\x18\x05 \x01(\t\x1a\x1d\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\"4\n\x11\x41liyunSMSResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xd3\x01\n\x03SMS\x12\x44\n\x08SMSAdmin\x12\x1d.jarvis.sms.AuAdminSMSRequest\x1a\x19.jarvis.sms.AuSMSResponse\x12<\n\x05SMSAu\x12\x18.jarvis.sms.AuSMSRequest\x1a\x19.jarvis.sms.AuSMSResponse\x12H\n\tSMSAliyun\x12\x1c.jarvis.sms.AliyunSMSRequest\x1a\x1d.jarvis.sms.AliyunSMSResponseB(\n\njarvis.smsB\x0eJarvisSMSProto\xa2\x02\tJARVISSMSb\x06proto3')
)




_AUSMSREQUEST = _descriptor.Descriptor(
  name='AuSMSRequest',
  full_name='jarvis.sms.AuSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_number', full_name='jarvis.sms.AuSMSRequest.mobile_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='jarvis.sms.AuSMSRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.AuSMSRequest.app', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=92,
)


_AUADMINSMSREQUEST = _descriptor.Descriptor(
  name='AuAdminSMSRequest',
  full_name='jarvis.sms.AuAdminSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='jarvis.sms.AuAdminSMSRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.AuAdminSMSRequest.app', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=143,
)


_AUSMSRESPONSE = _descriptor.Descriptor(
  name='AuSMSResponse',
  full_name='jarvis.sms.AuSMSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='jarvis.sms.AuSMSResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='jarvis.sms.AuSMSResponse.detail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=193,
)


_ALIYUNSMSREQUEST_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='jarvis.sms.AliyunSMSRequest.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='jarvis.sms.AliyunSMSRequest.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=392,
)

_ALIYUNSMSREQUEST = _descriptor.Descriptor(
  name='AliyunSMSRequest',
  full_name='jarvis.sms.AliyunSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile_numbers', full_name='jarvis.sms.AliyunSMSRequest.mobile_numbers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template_code', full_name='jarvis.sms.AliyunSMSRequest.template_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template_param', full_name='jarvis.sms.AliyunSMSRequest.template_param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business_id', full_name='jarvis.sms.AliyunSMSRequest.business_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app', full_name='jarvis.sms.AliyunSMSRequest.app', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ALIYUNSMSREQUEST_PHONENUMBER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=392,
)


_ALIYUNSMSRESPONSE = _descriptor.Descriptor(
  name='AliyunSMSResponse',
  full_name='jarvis.sms.AliyunSMSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='jarvis.sms.AliyunSMSResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='jarvis.sms.AliyunSMSResponse.detail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=446,
)

_ALIYUNSMSREQUEST_PHONENUMBER.containing_type = _ALIYUNSMSREQUEST
_ALIYUNSMSREQUEST.fields_by_name['mobile_numbers'].message_type = _ALIYUNSMSREQUEST_PHONENUMBER
DESCRIPTOR.message_types_by_name['AuSMSRequest'] = _AUSMSREQUEST
DESCRIPTOR.message_types_by_name['AuAdminSMSRequest'] = _AUADMINSMSREQUEST
DESCRIPTOR.message_types_by_name['AuSMSResponse'] = _AUSMSRESPONSE
DESCRIPTOR.message_types_by_name['AliyunSMSRequest'] = _ALIYUNSMSREQUEST
DESCRIPTOR.message_types_by_name['AliyunSMSResponse'] = _ALIYUNSMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuSMSRequest = _reflection.GeneratedProtocolMessageType('AuSMSRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuSMSRequest)
  })
_sym_db.RegisterMessage(AuSMSRequest)

AuAdminSMSRequest = _reflection.GeneratedProtocolMessageType('AuAdminSMSRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUADMINSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuAdminSMSRequest)
  })
_sym_db.RegisterMessage(AuAdminSMSRequest)

AuSMSResponse = _reflection.GeneratedProtocolMessageType('AuSMSResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUSMSRESPONSE,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AuSMSResponse)
  })
_sym_db.RegisterMessage(AuSMSResponse)

AliyunSMSRequest = _reflection.GeneratedProtocolMessageType('AliyunSMSRequest', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _ALIYUNSMSREQUEST_PHONENUMBER,
    '__module__' : 'sms_pb2'
    # @@protoc_insertion_point(class_scope:jarvis.sms.AliyunSMSRequest.PhoneNumber)
    })
  ,
  'DESCRIPTOR' : _ALIYUNSMSREQUEST,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AliyunSMSRequest)
  })
_sym_db.RegisterMessage(AliyunSMSRequest)
_sym_db.RegisterMessage(AliyunSMSRequest.PhoneNumber)

AliyunSMSResponse = _reflection.GeneratedProtocolMessageType('AliyunSMSResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALIYUNSMSRESPONSE,
  '__module__' : 'sms_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.sms.AliyunSMSResponse)
  })
_sym_db.RegisterMessage(AliyunSMSResponse)


DESCRIPTOR._options = None

_SMS = _descriptor.ServiceDescriptor(
  name='SMS',
  full_name='jarvis.sms.SMS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=449,
  serialized_end=660,
  methods=[
  _descriptor.MethodDescriptor(
    name='SMSAdmin',
    full_name='jarvis.sms.SMS.SMSAdmin',
    index=0,
    containing_service=None,
    input_type=_AUADMINSMSREQUEST,
    output_type=_AUSMSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SMSAu',
    full_name='jarvis.sms.SMS.SMSAu',
    index=1,
    containing_service=None,
    input_type=_AUSMSREQUEST,
    output_type=_AUSMSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SMSAliyun',
    full_name='jarvis.sms.SMS.SMSAliyun',
    index=2,
    containing_service=None,
    input_type=_ALIYUNSMSREQUEST,
    output_type=_ALIYUNSMSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMS)

DESCRIPTOR.services_by_name['SMS'] = _SMS

# @@protoc_insertion_point(module_scope)
